name: graphdot

channels:
  - conda-forge
  - pytorch
  - rdkit

dependencies:
  - python>=3.8
  - pip>=20.0.2
  - rdkit>=2020.03.1.0
  - scikit-learn>=0.24.1
  - hyperopt>=0.2.5
  - pip:
    - typed-argument-parser>=1.6.1
    - git+https://github.com/bp-kelley/descriptastorus
    - git+https://gitlab.com/Xiangyan93/graphdot.git@feature/xy
    - rxntools>=0.0.2
    - mgktools>=0.0.1
